package ru.lottery.util.constant;

public enum Env {
  DB_URL,
  DB_USER,
  DB_PASSWORD,
  DB_POOL_SIZE,
  DB_POOL_MIN_IDLE,
  DB_POOL_IDLE_TIMEOUT,
  DB_CONNECTION_TIMEOUT,
  JWT_SECRET,

  LIQUIBASE_MIGRATION_SCHEMA,
  LIQUIBASE_TARGET_SCHEMA,

  HIBERNATE_SHOW_SQL,
  HIBERNATE_FORMAT_SQL,
  HIBERNATE_DDL_AUTO_STRATEGY,
  HIBERNATE_DEFAULT_SCHEMA
}
